"""add_ai_questions_reset_fields

Revision ID: 0df05f01c61f
Revises: 229e0177563b
Create Date: 2025-12-02 01:16:13.101106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df05f01c61f'
down_revision: Union[str, Sequence[str], None] = '229e0177563b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_questions_reset_used', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_questions_reset_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('subscription_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('subscription_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'"),
               existing_nullable=False)
        batch_op.alter_column('trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'free'"),
               existing_nullable=False)
        batch_op.drop_column('ai_questions_reset_at')
        batch_op.drop_column('ai_questions_reset_used')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'KZT'"),
               existing_nullable=False)

    # ### end Alembic commands ###
