"""change_ai_questions_reset_to_skips

Revision ID: 4d07f5e05a65
Revises: 0df05f01c61f
Create Date: 2025-12-02 01:25:25.587392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d07f5e05a65'
down_revision: Union[str, Sequence[str], None] = '0df05f01c61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns first with default values
    op.add_column('user', sa.Column('ai_questions_skips_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('ai_questions_skips_reset_at', sa.DateTime(), nullable=True))
    
    # Update existing rows to have default value (in case server_default doesn't work)
    # Use proper table name quoting for PostgreSQL (user is a reserved word)
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('UPDATE "user" SET ai_questions_skips_count = 0 WHERE ai_questions_skips_count IS NULL')
    else:
        op.execute("UPDATE user SET ai_questions_skips_count = 0 WHERE ai_questions_skips_count IS NULL")
    
    # Drop old columns
    op.drop_column('user', 'ai_questions_reset_used')
    op.drop_column('user', 'ai_questions_reset_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add old columns back
    op.add_column('user', sa.Column('ai_questions_reset_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('ai_questions_reset_used', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    
    # Drop new columns
    op.drop_column('user', 'ai_questions_skips_reset_at')
    op.drop_column('user', 'ai_questions_skips_count')

    # ### end Alembic commands ###
