"""

Revision ID: a7969fb6d32f
Revises: 74de32d017b4
Create Date: 2025-11-08 13:23:04.796003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7969fb6d32f'
down_revision: Union[str, Sequence[str], None] = '74de32d017b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter user table to add new columns and make hashed_password nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
                              existing_type=sa.String(),
                              nullable=True)
        batch_op.add_column(sa.Column('google_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_google_id'), [
                              'google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_column('picture')
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')
        batch_op.alter_column('hashed_password',
                              existing_type=sa.String(),
                              nullable=False)
    # ### end Alembic commands ###
