"""

Revision ID: c4e50d898bde
Revises: cef05ff4eabf
Create Date: 2025-11-10 11:41:25.206091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e50d898bde'
down_revision: Union[str, Sequence[str], None] = 'cef05ff4eabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_summary',
                            sa.String(), nullable=True))
        batch_op.alter_column('is_draft',
                              existing_type=sa.BOOLEAN(),
                              server_default=None,
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('is_draft',
                              existing_type=sa.BOOLEAN(),
                              server_default=sa.text('0'),
                              existing_nullable=False)
        batch_op.drop_column('encrypted_summary')

    # ### end Alembic commands ###
